// /start page JavaScript — extracted from inline for CSP compliance

// Form handling
document.addEventListener('DOMContentLoaded', function() {
    var auditForm = document.getElementById('auditForm');
        var formSuccess = document.getElementById('formSuccess');

            if (auditForm) {
                    auditForm.addEventListener('submit', function(e) {
                                e.preventDefault();
                                            var formData = new FormData(this);
                                                        var data = {
                                                                        firstName: formData.get('firstName'),
                                                                                        email: formData.get('email'),
                                                                                                        company: formData.get('company')
                                                                                                                    };
                                                                                                                    
                                                                                                                                // Send to Make webhook
                                                                                                                                            fetch('https://hook.eu2.make.com/239twv22apw49upad8s150xjyaqumbr7', {
                                                                                                                                                            method: 'POST',
                                                                                                                                                                            headers: { 'Content-Type': 'application/json' },
                                                                                                                                                                                            body: JSON.stringify(data)
                                                                                                                                                                                                        }).then(function(response) {
                                                                                                                                                                                                                        console.log('Lead captured successfully:', response.status);
                                                                                                                                                                                                                                    }).catch(function(err) {
                                                                                                                                                                                                                                                    console.log('Form submitted (webhook may be inactive):', err.message);
                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                            // Show success message
                                                                                                                                                                                                                                                                                        auditForm.style.display = 'none';
                                                                                                                                                                                                                                                                                                    formSuccess.style.display = 'block';
                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                // Reset form after 5 seconds
                                                                                                                                                                                                                                                                                                                            setTimeout(function() {
                                                                                                                                                                                                                                                                                                                                            auditForm.reset();
                                                                                                                                                                                                                                                                                                                                                            auditForm.style.display = 'flex';
                                                                                                                                                                                                                                                                                                                                                                            formSuccess.style.display = 'none';
                                                                                                                                                                                                                                                                                                                                                                                        }, 5000);
                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                        // FAQ accordion
                                                                                                                                                                                                                                                                                                                                                                                                            document.querySelectorAll('.faq-question').forEach(function(question) {
                                                                                                                                                                                                                                                                                                                                                                                                                    question.addEventListener('click', function() {
                                                                                                                                                                                                                                                                                                                                                                                                                                var faqItem = this.parentElement;
                                                                                                                                                                                                                                                                                                                                                                                                                                            // Close all other items
                                                                                                                                                                                                                                                                                                                                                                                                                                                        document.querySelectorAll('.faq-item.active').forEach(function(item) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (item !== faqItem) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            item.classList.remove('active');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Toggle current item
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                faqItem.classList.toggle('active');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // CTA buttons — scroll to hero form
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    document.querySelectorAll('.btn-scroll-hero').forEach(function(btn) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            btn.addEventListener('click', function() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        document.getElementById('hero').scrollIntoView({ behavior: 'smooth' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Intersection Observer for fade-in animations
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            var observerOptions = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    threshold: 0.1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            rootMargin: '0px 0px -100px 0px'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    var observer = new IntersectionObserver(function(entries) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            entries.forEach(function(entry) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (entry.isIntersecting) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        entry.target.style.animation = 'fadeInUp 0.8s ease-out forwards';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        observer.unobserve(entry.target);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }, observerOptions);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    document.querySelectorAll('section').forEach(function(section) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            observer.observe(section);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
