[build]
  publish = "."

[[redirects]]
  from = "http://nextvibeai.com/*"
  to = "https://nextvibeai.com/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "all"
